default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_rails_react_dev
  username: postgres
  password: Takudzwa95!
  host: localhost

test:
  <<: *default
  database: hello_rails_react_test
  username: postgres
  password: Takudzwa95!
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
